before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/cli
    id: "ninjabot"
    binary: ninjabot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs('
      - '^test('
