// Code generated by tygo. DO NOT EDIT.
// Source: ui/dto.go — run `make generate` after changing the Go types.

//////////
// source: dto.go

/**
 * Candle is an OHLCV bar.
 */
export interface Candle {
  time: number /* int64 */;
  open: number /* float64 */;
  high: number /* float64 */;
  low: number /* float64 */;
  close: number /* float64 */;
  volume: number /* float64 */;
}
/**
 * Point is a single time/value sample of a series.
 */
export interface Point {
  time: number /* int64 */;
  value: number /* float64 */;
}
/**
 * Metric is one plotted series of an indicator (e.g. the signal line of MACD).
 * Style is one of: line, scatter, bar, histogram, waterfall.
 */
export interface Metric {
  name: string;
  color: string;
  style: string;
  points: Point[];
}
/**
 * Indicator groups the metrics of one indicator. Overlay indicators are drawn
 * on top of the price chart; the others get their own pane.
 */
export interface Indicator {
  name: string;
  overlay: boolean;
  metrics: Metric[];
}
/**
 * Order is the API projection of model.Order. CandleTime is the open time of
 * the candle that contains the order, so the UI can anchor markers to a bar.
 */
export interface Order {
  id: number /* int64 */;
  exchange_id: number /* int64 */;
  pair: string;
  side: string;
  type: string;
  status: string;
  price: number /* float64 */;
  quantity: number /* float64 */;
  fee: number /* float64 */;
  created_at: number /* int64 */;
  updated_at: number /* int64 */;
  candle_time: number /* int64 */;
  stop?: number /* float64 */;
  group_id?: number /* int64 */;
  ref_price: number /* float64 */;
  profit: number /* float64 */;
  profit_value: number /* float64 */;
}
/**
 * Drawdown is the maximum drawdown window of the paper wallet equity.
 */
export interface Drawdown {
  value: number /* float64 */;
  start: number /* int64 */;
  end: number /* int64 */;
}
/**
 * Snapshot is everything the dashboard needs to render one pair.
 */
export interface Snapshot {
  pair: string;
  asset: string;
  quote: string;
  candles: Candle[];
  indicators: Indicator[];
  orders: Order[];
  equity_values: Point[];
  asset_values: Point[];
  max_drawdown?: Drawdown;
}
/**
 * PairsResponse lists the pairs known by the dashboard.
 */
export interface PairsResponse {
  pairs: string[];
}
/**
 * MetricUpdate carries the latest point of one indicator metric.
 */
export interface MetricUpdate {
  name: string;
  point: Point;
}
/**
 * IndicatorUpdate carries the latest point of each metric of an indicator.
 */
export interface IndicatorUpdate {
  name: string;
  metrics: MetricUpdate[];
}
/**
 * CandleEvent is sent on the SSE stream (event: candle) when a candle closes.
 */
export interface CandleEvent {
  pair: string;
  candle: Candle;
  indicators: IndicatorUpdate[];
  equity?: Point;
  asset?: Point;
}
/**
 * OrderEvent is sent on the SSE stream (event: order) when an order is
 * created or updated.
 */
export interface OrderEvent {
  pair: string;
  order: Order;
}
/**
 * ControlsResponse reports whether the bot control panel is enabled and the
 * controller status ("running" or "stopped"). It is also the payload of the
 * SSE "controls" event, sent when the bot is started or stopped from the
 * dashboard.
 */
export interface ControlsResponse {
  enabled: boolean;
  status: string;
}
/**
 * ControlOrderRequest is the payload of POST /api/controls/order. Amount is
 * in quote currency; with Percent it is a percentage of the available balance
 * (quote balance for buys, asset balance for sells), mirroring the Telegram
 * /buy and /sell commands.
 */
export interface ControlOrderRequest {
  pair: string;
  side: string;
  amount: number /* float64 */;
  percent: boolean;
}
/**
 * ErrorResponse is the JSON body of API error replies.
 */
export interface ErrorResponse {
  error: string;
}
