package ui

import (
	"archive/tar"
	"bufio"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"runtime"
	"runtime/debug"
	"sort"
	"strconv"
	"strings"
	"time"

	log "github.com/sirupsen/logrus"
	"golang.org/x/mod/semver"
)

const (
	modulePath = "github.com/rodrigo-brito/ninjabot"

	// bundleAsset is the name of the release asset that contains the built
	// dashboard (output of `bun run build` in web/).
	bundleAsset = "ninjabot-ui.tar.gz"

	// checksumsAsset is generated by goreleaser and lists the SHA-256 of
	// every release asset, including bundleAsset.
	checksumsAsset = "checksums.txt"

	defaultReleaseURL = "https://github.com/rodrigo-brito/ninjabot/releases"

	// versionLatest asks GitHub for the most recent release.
	versionLatest = "latest"

	// versionLocal is reported when the bundle is served from a directory.
	versionLocal = "local"

	// completeMarker is written after a successful extraction; a cache
	// directory without it is considered corrupt and rebuilt.
	completeMarker = ".complete"

	// maxBundleSize protects against decompression bombs.
	maxBundleSize = 64 << 20
)

var (
	envUIDir     = "NINJABOT_UI_DIR"
	envUIVersion = "NINJABOT_UI_VERSION"

	// pseudoVersionRe matches the timestamp-hash tail of pseudo-versions:
	// vX.0.0-<time>-<hash>, vX.Y.Z-0.<time>-<hash>, vX.Y.Z-pre.0.<time>-<hash>.
	pseudoVersionRe = regexp.MustCompile(`[-.]\d{14}-[0-9a-f]{12}$`)
)

// bundleConfig is the resolved configuration of the bundle source.
type bundleConfig struct {
	dir        string
	version    string
	cacheDir   string
	releaseURL string
	client     *http.Client
}

// bundle is a resolved, ready-to-serve dashboard.
type bundle struct {
	// dir contains app.js, app.css and any other static asset.
	dir string
	// version is the release tag (or "local").
	version string
}

func defaultBundleConfig() bundleConfig {
	return bundleConfig{
		dir:        os.Getenv(envUIDir),
		version:    os.Getenv(envUIVersion),
		releaseURL: defaultReleaseURL,
		client:     &http.Client{Timeout: 5 * time.Minute},
	}
}

// resolveBundle returns the directory to serve the dashboard from,
// downloading and caching the release bundle when needed.
func resolveBundle(ctx context.Context, cfg bundleConfig) (bundle, error) {
	if cfg.dir != "" {
		return resolveLocalBundle(cfg.dir)
	}

	cacheDir := cfg.cacheDir
	if cacheDir == "" {
		base, err := os.UserCacheDir()
		if err != nil {
			return bundle{}, fmt.Errorf("cannot determine cache dir (set %s or use ui.WithCacheDir): %w", envUIDir, err)
		}
		cacheDir = filepath.Join(base, "ninjabot", "ui")
	}

	version := cfg.version
	if version == "" {
		detected := detectVersion()
		version = detected.version
		switch {
		case version == "":
			version = versionLatest
			log.Warnf("ui: cannot tell which ninjabot release this binary was built from (%s); "+
				"the dashboard bundle will be the latest release, which may not match this API. "+
				"To use your local build run `bun run build` in web/ and set %s=$PWD/web/dist, or pin a tag with %s=vX.Y.Z.",
				detected.reason, envUIDir, envUIVersion)
		case detected.inferred:
			log.Infof("ui: using dashboard %s (%s); set %s to override", version, detected.reason, envUIVersion)
		}
	}

	d := downloader{cfg: cfg, cacheDir: cacheDir}
	b, err := d.ensure(ctx, version)
	if err == nil {
		return b, nil
	}

	// Offline fallback: serve the newest bundle already cached.
	if cached, ok := newestCached(cacheDir); ok {
		log.Warnf("ui: could not fetch dashboard %s (%v); using cached %s", version, err, cached.version)
		return cached, nil
	}
	return bundle{}, err
}

func resolveLocalBundle(dir string) (bundle, error) {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return bundle{}, err
	}
	if _, err := os.Stat(filepath.Join(abs, "app.js")); err != nil {
		return bundle{}, fmt.Errorf("%s=%s does not contain app.js (run `bun run build` in web/): %w", envUIDir, dir, err)
	}
	return bundle{dir: abs, version: versionLocal}, nil
}

// detectedVersion is the outcome of detectVersion.
type detectedVersion struct {
	// version is a release tag, or "" when nothing could be inferred.
	version string
	// inferred is true when version is a best guess (nearest tag) rather
	// than the exact module version.
	inferred bool
	// reason explains where the version came from, for logs.
	reason string
}

// detectVersion figures out which ninjabot release the running binary was
// built from, in this order:
//
//  1. the exact version of the ninjabot module dependency (go.mod of the
//     user's project);
//  2. the nearest release before a pseudo-version (go get <commit>, or
//     `go build` of a local checkout, which Go 1.24+ stamps with a
//     VCS-derived pseudo-version);
//  3. `git describe` of the checkout when running from the repository
//     itself (`go run ./examples/...`) or through a replace directive.
func detectVersion() detectedVersion {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return detectedVersion{reason: "no build info"}
	}
	return detectVersionFrom(info, sourceDir(), gitDescribe)
}

// detectVersionFrom is detectVersion with its inputs injected (tests).
// checkoutDir is the directory of this source file at build time, when
// it still exists on disk; describe runs `git describe` in a directory.
func detectVersionFrom(info *debug.BuildInfo, checkoutDir string, describe func(dir string) string) detectedVersion {
	var module *debug.Module
	if info.Main.Path == modulePath {
		module = &info.Main
	} else {
		for _, dep := range info.Deps {
			if dep.Path == modulePath {
				module = dep
				break
			}
		}
	}
	if module == nil {
		return detectedVersion{reason: "ninjabot is not a dependency of this binary"}
	}

	if module.Replace != nil {
		// A replace pointing to a directory (no version) is a local checkout.
		if module.Replace.Path != "" && module.Replace.Version == "" {
			if tag := describe(module.Replace.Path); tag != "" {
				return detectedVersion{version: tag, inferred: true, reason: "nearest git tag of the replace directive " + module.Replace.Path}
			}
		}
		return detectedVersion{reason: "replace directive " + module.Replace.Path}
	}

	if isReleaseTag(module.Version) {
		return detectedVersion{version: module.Version, reason: "module version"}
	}

	if base := baseOfPseudoVersion(module.Version); base != "" {
		return detectedVersion{version: base, inferred: true, reason: "nearest release before " + module.Version}
	}

	// Only trust the source directory when the binary was built from the
	// repository itself (go run ./examples/...), never from the module cache.
	if checkoutDir != "" && info.Main.Path == modulePath {
		if tag := describe(checkoutDir); tag != "" {
			return detectedVersion{version: tag, inferred: true, reason: "nearest git tag of the local checkout"}
		}
	}

	return detectedVersion{reason: "development version " + module.Version}
}

// sourceDir returns the directory of this file as recorded at build time,
// or "" when it no longer exists (the binary runs elsewhere).
func sourceDir() string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return ""
	}
	dir := filepath.Dir(file)
	if _, err := os.Stat(filepath.Join(dir, "bundle.go")); err != nil {
		return ""
	}
	return dir
}

// gitDescribe returns the nearest reachable release tag of the repository
// containing dir, or "" when git or the repository are unavailable.
func gitDescribe(dir string) string {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "git", "-C", dir, "describe", "--tags", "--abbrev=0", "--match", "v[0-9]*")
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	tag := strings.TrimSpace(string(out))
	if !isReleaseTag(tag) {
		return ""
	}
	return tag
}

// baseOfPseudoVersion returns the release a pseudo-version was derived
// from: vX.Y.(Z+1)-0.<time>-<hash> comes after tag vX.Y.Z, and
// vX.Y.Z-pre.0.<time>-<hash> after pre-release vX.Y.Z-pre. Build metadata
// such as +dirty or +incompatible is ignored. Returns "" for versions that
// are not pseudo-versions or have no tag before them (v0.0.0-...).
func baseOfPseudoVersion(v string) string {
	v = strings.SplitN(v, "+", 2)[0]
	if !pseudoVersionRe.MatchString(v) || !semver.IsValid(v) {
		return ""
	}
	pre := semver.Prerelease(v) // "-0.20060102150405-abcdef123456" or "-pre.0.2006...-abc"
	core := strings.TrimSuffix(v, pre)
	suffix := pseudoVersionRe.FindString(v) // ".2006...-abc" (or "-2006...-abc" for vX.0.0)
	pre = strings.TrimSuffix(pre, suffix)   // "-0", "-pre.0" or "" (no tag before)

	if pre == "-0" {
		// after tag vX.Y.(Z-1)
		parts := strings.Split(strings.TrimPrefix(core, "v"), ".")
		if len(parts) != 3 {
			return ""
		}
		patch, err := strconv.Atoi(parts[2])
		if err != nil || patch == 0 {
			// v0.0.0-<time>-<hash>: no tag before this commit
			if parts[0] == "0" && parts[1] == "0" {
				return ""
			}
			return ""
		}
		return fmt.Sprintf("v%s.%s.%d", parts[0], parts[1], patch-1)
	}
	if strings.HasSuffix(pre, ".0") {
		// after pre-release vX.Y.Z-pre
		return core + strings.TrimSuffix(pre, ".0")
	}
	return ""
}

func isReleaseTag(v string) bool {
	if !semver.IsValid(v) || semver.Build(v) != "" {
		return false
	}
	if strings.HasSuffix(v, "+incompatible") || pseudoVersionRe.MatchString(v) {
		return false
	}
	return true
}

type downloader struct {
	cfg      bundleConfig
	cacheDir string
}

// ensure returns the cached bundle for version, downloading it first when
// missing. "latest" is resolved to a concrete tag through the GitHub redirect.
func (d downloader) ensure(ctx context.Context, version string) (bundle, error) {
	if version == versionLatest {
		tag, err := d.resolveLatest(ctx)
		if err != nil {
			return bundle{}, fmt.Errorf("resolving latest dashboard release: %w", err)
		}
		version = tag
	}

	dir := filepath.Join(d.cacheDir, version)
	if isComplete(dir) {
		return bundle{dir: dir, version: version}, nil
	}

	log.Infof("ui: downloading dashboard %s to %s", version, dir)
	if err := d.download(ctx, version, dir); err != nil {
		return bundle{}, fmt.Errorf("downloading dashboard %s: %w", version, err)
	}
	return bundle{dir: dir, version: version}, nil
}

func isComplete(dir string) bool {
	_, err := os.Stat(filepath.Join(dir, completeMarker))
	return err == nil
}

// resolveLatest follows GitHub's "latest" redirect without the API, so it
// is not subject to API rate limits.
func (d downloader) resolveLatest(ctx context.Context) (string, error) {
	client := *d.cfg.client
	client.CheckRedirect = func(*http.Request, []*http.Request) error {
		return http.ErrUseLastResponse
	}

	url := d.cfg.releaseURL + "/latest/download/" + bundleAsset
	req, err := http.NewRequestWithContext(ctx, http.MethodHead, url, nil)
	if err != nil {
		return "", err
	}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	location := resp.Header.Get("Location")
	if resp.StatusCode < 300 || resp.StatusCode >= 400 || location == "" {
		return "", fmt.Errorf("unexpected response %s for %s", resp.Status, url)
	}

	// .../releases/download/<tag>/ninjabot-ui.tar.gz
	tag := path.Base(path.Dir(location))
	if !isReleaseTag(tag) {
		return "", fmt.Errorf("cannot parse release tag from %s", location)
	}
	return tag, nil
}

func (d downloader) assetURL(version, asset string) string {
	return d.cfg.releaseURL + "/download/" + version + "/" + asset
}

func (d downloader) fetch(ctx context.Context, url string) (io.ReadCloser, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	resp, err := d.cfg.client.Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		resp.Body.Close()
		return nil, fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	return resp.Body, nil
}

// download fetches the checksum list and the bundle, verifies the SHA-256
// and extracts it atomically into dir.
func (d downloader) download(ctx context.Context, version, dir string) error {
	expected, err := d.expectedChecksum(ctx, version)
	if err != nil {
		return err
	}

	body, err := d.fetch(ctx, d.assetURL(version, bundleAsset))
	if err != nil {
		return err
	}
	defer body.Close()

	if err := os.MkdirAll(d.cacheDir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(d.cacheDir, "bundle-*.tar.gz")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	defer tmp.Close()

	hash := sha256.New()
	if _, err := io.Copy(io.MultiWriter(tmp, hash), io.LimitReader(body, maxBundleSize)); err != nil {
		return err
	}
	if got := hex.EncodeToString(hash.Sum(nil)); got != expected {
		return fmt.Errorf("checksum mismatch for %s: expected %s, got %s", bundleAsset, expected, got)
	}
	if _, err := tmp.Seek(0, io.SeekStart); err != nil {
		return err
	}

	stage, err := os.MkdirTemp(d.cacheDir, "extract-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(stage)

	if err := extractTarGz(tmp, stage); err != nil {
		return fmt.Errorf("extracting %s: %w", bundleAsset, err)
	}
	if _, err := os.Stat(filepath.Join(stage, "app.js")); err != nil {
		return fmt.Errorf("%s does not contain app.js", bundleAsset)
	}
	if err := os.WriteFile(filepath.Join(stage, completeMarker), []byte(version+"\n"), 0o644); err != nil {
		return err
	}

	_ = os.RemoveAll(dir)
	if err := os.Rename(stage, dir); err != nil {
		return err
	}
	return nil
}

func (d downloader) expectedChecksum(ctx context.Context, version string) (string, error) {
	body, err := d.fetch(ctx, d.assetURL(version, checksumsAsset))
	if err != nil {
		return "", err
	}
	defer body.Close()

	scanner := bufio.NewScanner(body)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) == 2 && fields[1] == bundleAsset {
			return strings.ToLower(fields[0]), nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", err
	}
	return "", fmt.Errorf("%s has no entry for %s", checksumsAsset, bundleAsset)
}

// extractTarGz unpacks a tar.gz into dir, rejecting paths that escape it.
func extractTarGz(r io.Reader, dir string) error {
	gz, err := gzip.NewReader(r)
	if err != nil {
		return err
	}
	defer gz.Close()

	var total int64
	tr := tar.NewReader(gz)
	for {
		header, err := tr.Next()
		if errors.Is(err, io.EOF) {
			return nil
		}
		if err != nil {
			return err
		}

		name := filepath.Clean(header.Name)
		if name == "." || name == "" {
			continue
		}
		if filepath.IsAbs(name) || strings.HasPrefix(name, "..") {
			return fmt.Errorf("illegal path in archive: %s", header.Name)
		}
		target := filepath.Join(dir, name)

		switch header.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0o755); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			f, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
			if err != nil {
				return err
			}
			n, err := io.Copy(f, io.LimitReader(tr, maxBundleSize-total))
			f.Close()
			if err != nil {
				return err
			}
			total += n
			if total >= maxBundleSize {
				return fmt.Errorf("archive larger than %d bytes", maxBundleSize)
			}
		default:
			// symlinks, devices, etc. are not expected in the bundle
			continue
		}
	}
}

// newestCached returns the cached bundle with the highest version.
func newestCached(cacheDir string) (bundle, bool) {
	entries, err := os.ReadDir(cacheDir)
	if err != nil {
		return bundle{}, false
	}
	versions := make([]string, 0)
	for _, entry := range entries {
		if entry.IsDir() && isReleaseTag(entry.Name()) && isComplete(filepath.Join(cacheDir, entry.Name())) {
			versions = append(versions, entry.Name())
		}
	}
	if len(versions) == 0 {
		return bundle{}, false
	}
	sort.Slice(versions, func(i, j int) bool { return semver.Compare(versions[i], versions[j]) > 0 })
	return bundle{dir: filepath.Join(cacheDir, versions[0]), version: versions[0]}, true
}
