package ui

import (
	"archive/tar"
	"bufio"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"runtime/debug"
	"sort"
	"strings"
	"time"

	log "github.com/sirupsen/logrus"
	"golang.org/x/mod/semver"
)

const (
	modulePath = "github.com/rodrigo-brito/ninjabot"

	// bundleAsset is the name of the release asset that contains the built
	// dashboard (output of `bun run build` in web/).
	bundleAsset = "ninjabot-ui.tar.gz"

	// checksumsAsset is generated by goreleaser and lists the SHA-256 of
	// every release asset, including bundleAsset.
	checksumsAsset = "checksums.txt"

	defaultReleaseURL = "https://github.com/rodrigo-brito/ninjabot/releases"

	// versionLatest asks GitHub for the most recent release.
	versionLatest = "latest"

	// versionLocal is reported when the bundle is served from a directory.
	versionLocal = "local"

	// completeMarker is written after a successful extraction; a cache
	// directory without it is considered corrupt and rebuilt.
	completeMarker = ".complete"

	// maxBundleSize protects against decompression bombs.
	maxBundleSize = 64 << 20
)

var (
	envUIDir     = "NINJABOT_UI_DIR"
	envUIVersion = "NINJABOT_UI_VERSION"

	// pseudoVersionRe matches versions generated by `go get <commit>`.
	pseudoVersionRe = regexp.MustCompile(`-\d{14}-[0-9a-f]{12}$`)
)

// bundleConfig is the resolved configuration of the bundle source.
type bundleConfig struct {
	dir        string
	version    string
	cacheDir   string
	releaseURL string
	client     *http.Client
}

// bundle is a resolved, ready-to-serve dashboard.
type bundle struct {
	// dir contains app.js, app.css and any other static asset.
	dir string
	// version is the release tag (or "local").
	version string
}

func defaultBundleConfig() bundleConfig {
	return bundleConfig{
		dir:        os.Getenv(envUIDir),
		version:    os.Getenv(envUIVersion),
		releaseURL: defaultReleaseURL,
		client:     &http.Client{Timeout: 5 * time.Minute},
	}
}

// resolveBundle returns the directory to serve the dashboard from,
// downloading and caching the release bundle when needed.
func resolveBundle(ctx context.Context, cfg bundleConfig) (bundle, error) {
	if cfg.dir != "" {
		return resolveLocalBundle(cfg.dir)
	}

	cacheDir := cfg.cacheDir
	if cacheDir == "" {
		base, err := os.UserCacheDir()
		if err != nil {
			return bundle{}, fmt.Errorf("cannot determine cache dir (set %s or use ui.WithCacheDir): %w", envUIDir, err)
		}
		cacheDir = filepath.Join(base, "ninjabot", "ui")
	}

	version := cfg.version
	if version == "" {
		version = moduleVersion()
		if version == "" {
			version = versionLatest
			log.Warnf("ui: ninjabot is compiled from a development version (replace directive, pseudo-version or local checkout); "+
				"the dashboard bundle will be the latest release, which may not match this API. "+
				"To use your local build run `bun run build` in web/ and set %s=$PWD/web/dist, or pin a tag with %s=vX.Y.Z.",
				envUIDir, envUIVersion)
		}
	}

	d := downloader{cfg: cfg, cacheDir: cacheDir}
	b, err := d.ensure(ctx, version)
	if err == nil {
		return b, nil
	}

	// Offline fallback: serve the newest bundle already cached.
	if cached, ok := newestCached(cacheDir); ok {
		log.Warnf("ui: could not fetch dashboard %s (%v); using cached %s", version, err, cached.version)
		return cached, nil
	}
	return bundle{}, err
}

func resolveLocalBundle(dir string) (bundle, error) {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return bundle{}, err
	}
	if _, err := os.Stat(filepath.Join(abs, "app.js")); err != nil {
		return bundle{}, fmt.Errorf("%s=%s does not contain app.js (run `bun run build` in web/): %w", envUIDir, dir, err)
	}
	return bundle{dir: abs, version: versionLocal}, nil
}

// moduleVersion returns the release tag of the ninjabot module compiled into
// the running binary, or "" when it is not a tagged release.
func moduleVersion() string {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return ""
	}
	return releaseVersion(info)
}

func releaseVersion(info *debug.BuildInfo) string {
	if info.Main.Path == modulePath {
		// Built from inside the repository (examples, tests): no tag.
		return ""
	}
	for _, dep := range info.Deps {
		if dep.Path != modulePath {
			continue
		}
		if dep.Replace != nil {
			return ""
		}
		if isReleaseTag(dep.Version) {
			return dep.Version
		}
		return ""
	}
	return ""
}

func isReleaseTag(v string) bool {
	if !semver.IsValid(v) || semver.Build(v) != "" {
		return false
	}
	if strings.HasSuffix(v, "+incompatible") || pseudoVersionRe.MatchString(v) {
		return false
	}
	return true
}

type downloader struct {
	cfg      bundleConfig
	cacheDir string
}

// ensure returns the cached bundle for version, downloading it first when
// missing. "latest" is resolved to a concrete tag through the GitHub redirect.
func (d downloader) ensure(ctx context.Context, version string) (bundle, error) {
	if version == versionLatest {
		tag, err := d.resolveLatest(ctx)
		if err != nil {
			return bundle{}, fmt.Errorf("resolving latest dashboard release: %w", err)
		}
		version = tag
	}

	dir := filepath.Join(d.cacheDir, version)
	if isComplete(dir) {
		return bundle{dir: dir, version: version}, nil
	}

	log.Infof("ui: downloading dashboard %s to %s", version, dir)
	if err := d.download(ctx, version, dir); err != nil {
		return bundle{}, fmt.Errorf("downloading dashboard %s: %w", version, err)
	}
	return bundle{dir: dir, version: version}, nil
}

func isComplete(dir string) bool {
	_, err := os.Stat(filepath.Join(dir, completeMarker))
	return err == nil
}

// resolveLatest follows GitHub's "latest" redirect without the API, so it
// is not subject to API rate limits.
func (d downloader) resolveLatest(ctx context.Context) (string, error) {
	client := *d.cfg.client
	client.CheckRedirect = func(*http.Request, []*http.Request) error {
		return http.ErrUseLastResponse
	}

	url := d.cfg.releaseURL + "/latest/download/" + bundleAsset
	req, err := http.NewRequestWithContext(ctx, http.MethodHead, url, nil)
	if err != nil {
		return "", err
	}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	location := resp.Header.Get("Location")
	if resp.StatusCode < 300 || resp.StatusCode >= 400 || location == "" {
		return "", fmt.Errorf("unexpected response %s for %s", resp.Status, url)
	}

	// .../releases/download/<tag>/ninjabot-ui.tar.gz
	tag := path.Base(path.Dir(location))
	if !isReleaseTag(tag) {
		return "", fmt.Errorf("cannot parse release tag from %s", location)
	}
	return tag, nil
}

func (d downloader) assetURL(version, asset string) string {
	return d.cfg.releaseURL + "/download/" + version + "/" + asset
}

func (d downloader) fetch(ctx context.Context, url string) (io.ReadCloser, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	resp, err := d.cfg.client.Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		resp.Body.Close()
		return nil, fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	return resp.Body, nil
}

// download fetches the checksum list and the bundle, verifies the SHA-256
// and extracts it atomically into dir.
func (d downloader) download(ctx context.Context, version, dir string) error {
	expected, err := d.expectedChecksum(ctx, version)
	if err != nil {
		return err
	}

	body, err := d.fetch(ctx, d.assetURL(version, bundleAsset))
	if err != nil {
		return err
	}
	defer body.Close()

	if err := os.MkdirAll(d.cacheDir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(d.cacheDir, "bundle-*.tar.gz")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	defer tmp.Close()

	hash := sha256.New()
	if _, err := io.Copy(io.MultiWriter(tmp, hash), io.LimitReader(body, maxBundleSize)); err != nil {
		return err
	}
	if got := hex.EncodeToString(hash.Sum(nil)); got != expected {
		return fmt.Errorf("checksum mismatch for %s: expected %s, got %s", bundleAsset, expected, got)
	}
	if _, err := tmp.Seek(0, io.SeekStart); err != nil {
		return err
	}

	stage, err := os.MkdirTemp(d.cacheDir, "extract-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(stage)

	if err := extractTarGz(tmp, stage); err != nil {
		return fmt.Errorf("extracting %s: %w", bundleAsset, err)
	}
	if _, err := os.Stat(filepath.Join(stage, "app.js")); err != nil {
		return fmt.Errorf("%s does not contain app.js", bundleAsset)
	}
	if err := os.WriteFile(filepath.Join(stage, completeMarker), []byte(version+"\n"), 0o644); err != nil {
		return err
	}

	_ = os.RemoveAll(dir)
	if err := os.Rename(stage, dir); err != nil {
		return err
	}
	return nil
}

func (d downloader) expectedChecksum(ctx context.Context, version string) (string, error) {
	body, err := d.fetch(ctx, d.assetURL(version, checksumsAsset))
	if err != nil {
		return "", err
	}
	defer body.Close()

	scanner := bufio.NewScanner(body)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) == 2 && fields[1] == bundleAsset {
			return strings.ToLower(fields[0]), nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", err
	}
	return "", fmt.Errorf("%s has no entry for %s", checksumsAsset, bundleAsset)
}

// extractTarGz unpacks a tar.gz into dir, rejecting paths that escape it.
func extractTarGz(r io.Reader, dir string) error {
	gz, err := gzip.NewReader(r)
	if err != nil {
		return err
	}
	defer gz.Close()

	var total int64
	tr := tar.NewReader(gz)
	for {
		header, err := tr.Next()
		if errors.Is(err, io.EOF) {
			return nil
		}
		if err != nil {
			return err
		}

		name := filepath.Clean(header.Name)
		if name == "." || name == "" {
			continue
		}
		if filepath.IsAbs(name) || strings.HasPrefix(name, "..") {
			return fmt.Errorf("illegal path in archive: %s", header.Name)
		}
		target := filepath.Join(dir, name)

		switch header.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0o755); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			f, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
			if err != nil {
				return err
			}
			n, err := io.Copy(f, io.LimitReader(tr, maxBundleSize-total))
			f.Close()
			if err != nil {
				return err
			}
			total += n
			if total >= maxBundleSize {
				return fmt.Errorf("archive larger than %d bytes", maxBundleSize)
			}
		default:
			// symlinks, devices, etc. are not expected in the bundle
			continue
		}
	}
}

// newestCached returns the cached bundle with the highest version.
func newestCached(cacheDir string) (bundle, bool) {
	entries, err := os.ReadDir(cacheDir)
	if err != nil {
		return bundle{}, false
	}
	versions := make([]string, 0)
	for _, entry := range entries {
		if entry.IsDir() && isReleaseTag(entry.Name()) && isComplete(filepath.Join(cacheDir, entry.Name())) {
			versions = append(versions, entry.Name())
		}
	}
	if len(versions) == 0 {
		return bundle{}, false
	}
	sort.Slice(versions, func(i, j int) bool { return semver.Compare(versions[i], versions[j]) > 0 })
	return bundle{dir: filepath.Join(cacheDir, versions[0]), version: versions[0]}, true
}
